/**
 * @fileoverview generateTypes 模块测试
 *
 * 测试 TypeScript 类型生成功能，包括：
 * - RouteIndexMap 类型生成
 * - 动态参数类型生成
 * - .d.ts 文件生成
 */
import { describe, expect, it } from 'vitest'
import { generateFullDtsFile } from '../../../src/vite/core/generateTypes.js'
import type { ParsedPage } from '../../../src/vite/core/types.js'

function createMockParsedPage(overrides: Partial<ParsedPage> = {}): ParsedPage {
  return {
    path: '/',
    filePath: '/src/pages/index.tsx',
    name: 'home',
    params: [],
    isIndex: true,
    isDynamic: false,
    children: [],
    parentPath: '',
    ...overrides
  }
}

describe('generateFullDtsFile', () => {
  describe('文件头生成', () => {
    it('应该生成正确的文件头注释', () => {
      const pages: ParsedPage[] = [createMockParsedPage({ path: '/', name: 'home' })]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain('/* eslint-disable */')
      expect(dts).toContain('/* prettier-ignore */')
      expect(dts).toContain('// @ts-nocheck')
      expect(dts).toContain('// Generated by vitarx-router')
    })
  })

  describe('模块声明生成', () => {
    it('应该生成正确的模块扩展声明', () => {
      const pages: ParsedPage[] = [createMockParsedPage({ path: '/', name: 'home' })]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain("declare module 'vitarx-router'")
      expect(dts).toContain('interface RouteIndexMap')
    })
  })

  describe('RouteIndexMap 类型生成', () => {
    it('应该为静态路由生成空对象类型', () => {
      const pages: ParsedPage[] = [createMockParsedPage({ path: '/', name: 'home' })]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain("'home': {}")
      expect(dts).toContain("'/': {}")
    })

    it('应该为动态路由生成参数类型（仅注册 name，不注册 path）', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/user/{id}',
          name: 'user-id',
          isIndex: false,
          isDynamic: true,
          params: ['id']
        })
      ]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain("'user-id': { params: { id: string | number } }")
      expect(dts).not.toContain("'/user/{id}'")
    })

    it('应该正确处理多个动态参数', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/post/{category}/{slug}',
          name: 'post-slug',
          isIndex: false,
          isDynamic: true,
          params: ['category', 'slug']
        })
      ]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain('category: string | number')
      expect(dts).toContain('slug: string | number')
    })
  })

  describe('多个路由类型生成', () => {
    it('应该为所有路由生成类型', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({ path: '/', name: 'home' }),
        createMockParsedPage({ path: '/about', name: 'about', isIndex: false }),
        createMockParsedPage({
          path: '/user/{id}',
          name: 'user-id',
          isIndex: false,
          isDynamic: true,
          params: ['id']
        })
      ]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain("'home': {}")
      expect(dts).toContain("'about': {}")
      expect(dts).toContain("'user-id': { params: { id: string | number } }")
    })
  })

  describe('嵌套路由类型生成', () => {
    it('应该为嵌套路由生成类型（父路由有 children 不注册）', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/user',
          name: 'user',
          children: [
            createMockParsedPage({
              path: '/user/{id}',
              name: 'user-id',
              isIndex: false,
              isDynamic: true,
              params: ['id']
            })
          ]
        })
      ]

      const dts = generateFullDtsFile(pages)

      expect(dts).not.toContain("'user': {}")
      expect(dts).toContain("'user-id': { params: { id: string | number } }")
    })

    it('应该为有 redirect 的父路由生成类型', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/user',
          name: 'user',
          redirect: '/user/list',
          children: [
            createMockParsedPage({
              path: '/user/list',
              name: 'user-list',
              isIndex: false
            })
          ]
        })
      ]

      const dts = generateFullDtsFile(pages)

      expect(dts).toContain("'user': {}")
      expect(dts).toContain("'/user': {}")
      expect(dts).toContain("'user-list': {}")
      expect(dts).toContain("'/user/list': {}")
    })

    it('应该正确处理空路径子路由（使用父路径）', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/admin',
          name: 'admin',
          children: [
            createMockParsedPage({
              path: '',
              name: 'admin-index',
              isIndex: true,
              parentPath: '/admin'
            })
          ]
        })
      ]

      const dts = generateFullDtsFile(pages)

      expect(dts).not.toContain("'admin': {}")
      expect(dts).toContain("'admin-index': {}")
      expect(dts).toContain("'/admin': {}")
      expect(dts).not.toContain("'': {}")
    })
  })

  describe('完整文件生成', () => {
    it('应该生成完整的 .d.ts 文件内容', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({ path: '/', name: 'home' }),
        createMockParsedPage({
          path: '/user/{id}',
          name: 'user-id',
          isIndex: false,
          isDynamic: true,
          params: ['id']
        })
      ]

      const dts = generateFullDtsFile(pages)

      // 检查文件头
      expect(dts).toContain('// Generated by vitarx-router')

      // 检查模块声明
      expect(dts).toContain("declare module 'vitarx-router'")

      // 检查类型定义
      expect(dts).toContain('interface RouteIndexMap')
      expect(dts).toContain("'home': {}")
      expect(dts).toContain("'user-id': { params: { id: string | number } }")
    })
  })

  describe('alias 别名类型映射', () => {
    it('应该为字符串 alias 生成类型映射', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/home',
          name: 'home',
          isIndex: false,
          alias: '/index'
        })
      ]

      const dts = generateFullDtsFile(pages)

      // name 映射
      expect(dts).toContain("'home': {}")
      // path 映射
      expect(dts).toContain("'/home': {}")
      // alias 映射
      expect(dts).toContain("'/index': {}")
    })

    it('应该为数组 alias 生成类型映射', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/home',
          name: 'home',
          isIndex: false,
          alias: ['/index', '/main']
        })
      ]

      const dts = generateFullDtsFile(pages)

      // name 映射
      expect(dts).toContain("'home': {}")
      // path 映射
      expect(dts).toContain("'/home': {}")
      // alias 映射
      expect(dts).toContain("'/index': {}")
      expect(dts).toContain("'/main': {}")
    })

    it('应该正确处理相对路径 alias', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/home',
          name: 'home',
          isIndex: false,
          alias: 'index' // 相对路径
        })
      ]

      const dts = generateFullDtsFile(pages)

      // name 映射
      expect(dts).toContain("'home': {}")
      // path 映射
      expect(dts).toContain("'/home': {}")
      // alias 映射（相对路径解析为 /index）
      expect(dts).toContain("'/index': {}")
    })

    it('应该正确处理空字符串 alias', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/home',
          name: 'home',
          isIndex: false,
          parentPath: '',
          alias: '' // 空字符串
        })
      ]

      const dts = generateFullDtsFile(pages)

      // 空字符串 alias 使用父路径（根路径 /）
      expect(dts).toContain("'home': {}")
      expect(dts).toContain("'/home': {}")
    })

    it('应该正确处理嵌套路由的 alias', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/admin',
          name: 'admin',
          children: [
            createMockParsedPage({
              path: '/admin/users',
              name: 'admin-users',
              isIndex: false,
              parentPath: '/admin',
              alias: ['list', '/manage']
            })
          ]
        })
      ]

      const dts = generateFullDtsFile(pages)

      // 子路由 name 映射
      expect(dts).toContain("'admin-users': {}")
      // 子路由 path 映射
      expect(dts).toContain("'/admin/users': {}")
      // alias 映射：相对路径 'list' 解析为 '/admin/list'
      expect(dts).toContain("'/admin/list': {}")
      // alias 映射：绝对路径 '/manage'
      expect(dts).toContain("'/manage': {}")
    })

    it('动态参数 alias 不应该生成 path 映射', () => {
      const pages: ParsedPage[] = [
        createMockParsedPage({
          path: '/user/{id}',
          name: 'user-id',
          isIndex: false,
          isDynamic: true,
          params: ['id'],
          alias: '/member/{id}'
        })
      ]

      const dts = generateFullDtsFile(pages)

      // name 映射应该存在
      expect(dts).toContain("'user-id': { params: { id: string | number } }")
      // 动态参数的 path 不应该生成映射
      expect(dts).not.toContain("'/user/{id}'")
      // 动态参数的 alias 也不应该生成映射
      expect(dts).not.toContain("'/member/{id}'")
    })
  })
})
