/**
 * @fileoverview 类型生成模块
 *
 * 负责生成路由的 TypeScript 类型定义，用于提供 IDE 类型提示和编译时类型检查。
 */
import { extractParamsFromPath } from './parsePage.js'
import type { ParsedPage, RouteIndexMap } from './types.js'

/**
 * 检查路径是否包含动态参数
 * @param path - 路由路径
 * @returns 是否包含动态参数
 */
function hasDynamicParams(path: string): boolean {
  return /\{[^}]+}/.test(path)
}

/**
 * 判断路由是否需要注册
 * 规则：有 component 且没有 children，或者有 redirect
 * @param page - 页面信息
 * @returns 是否需要注册
 */
function shouldRegisterRoute(page: ParsedPage): boolean {
  const hasComponent = page.filePath && page.filePath.trim() !== ''
  const hasChildren = page.children.length > 0
  const hasRedirect = page.redirect !== undefined
  return (hasComponent && !hasChildren) || hasRedirect
}

/**
 * 递归处理单个页面及其子页面
 *
 * @param map - 路由索引映射表
 * @param page - 要处理的页面
 * @param parentFullPath - 父级完整路径（用于计算空路径子路由的完整路径）
 */
function processPage(map: RouteIndexMap, page: ParsedPage, parentFullPath: string = ''): void {
  if (shouldRegisterRoute(page)) {
    const params = extractParamsFromPath(page.path)
    const entry =
      params.length > 0
        ? { params: params.reduce((acc, p) => ({ ...acc, [p]: 'string | number' }), {}) }
        : {}

    map[page.name] = entry

    if (!hasDynamicParams(page.path)) {
      let fullPath = page.path
      if (page.path === '' && parentFullPath) {
        fullPath = parentFullPath
      }
      if (fullPath) {
        map[fullPath] = entry
      }
    }
  }

  const currentFullPath = page.path === '' ? parentFullPath : page.path || parentFullPath

  for (const child of page.children) {
    processPage(map, child, currentFullPath)
  }
}

/**
 * 构建路由索引映射表
 *
 * 将页面列表转换为 RouteIndexMap 对象，包含每个路由的名称和路径作为键，以及对应的参数类型信息作为值。
 *
 * 注册规则：
 * 1. 有 component 且没有 children 的路由需要注册
 * 2. 有 redirect 的路由需要注册
 * 3. 如果 path 包含动态参数（如 {id}），只注册 name 映射，不注册 path 映射
 * 4. 空路径的子路由使用完整路径
 *
 * @param pages - 解析后的页面列表
 * @returns 路由索引映射表
 */
function buildRouteIndexMap(pages: ParsedPage[]): RouteIndexMap {
  const map: RouteIndexMap = {}
  for (const page of pages) {
    processPage(map, page)
  }
  return map
}

/**
 * 格式化单个路由索引条目
 *
 * @param key - 路由名称或路径
 * @param value - 路由索引条目值
 * @returns 格式化后的条目字符串
 */
function formatRouteIndexEntry(
  key: string,
  value: { params?: Record<string, string | number> }
): string {
  if (value.params && Object.keys(value.params).length > 0) {
    const paramsStr = Object.entries(value.params)
      .map(([k, v]) => `${k}: ${v}`)
      .join(', ')
    return `'${key}': { params: { ${paramsStr} } }`
  }
  return `'${key}': {}`
}

/**
 * 生成完整的 .d.ts 声明文件内容
 *
 * 包含文件头注释、模块扩展声明和具体的 RouteIndexMap 类型定义。
 * 生成的文件应该被用户项目的 TypeScript 配置引用。
 *
 * @param pages - 解析后的页面列表
 * @returns 完整的 .d.ts 文件内容
 */
export function generateFullDtsFile(pages: ParsedPage[]): string {
  const indexMap = buildRouteIndexMap(pages)

  const lines: string[] = []

  // 文件头注释
  lines.push('/* eslint-disable */')
  lines.push('/* prettier-ignore */')
  lines.push('// @ts-nocheck')
  lines.push('// Generated by vitarx-router. Do not modify this file.')
  lines.push('')

  // 模块扩展声明 - 扩展 vitarx-router 中的 RouteIndexMap 接口
  lines.push("declare module 'vitarx-router' {")
  lines.push('  // 自动生成的路由索引映射类型')
  lines.push('  interface RouteIndexMap {')

  const entries = Object.entries(indexMap)
  for (let i = 0; i < entries.length; i++) {
    const [key, value] = entries[i]
    const comma = i < entries.length - 1 ? ',' : ''
    const line = formatRouteIndexEntry(key, value)
    lines.push(`    ${line}${comma}`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')

  return lines.join('\n')
}
