/**
 * @fileoverview 类型生成模块
 *
 * 负责生成路由的 TypeScript 类型定义，用于提供 IDE 类型提示和编译时类型检查。
 */
import { extractParamsFromPath } from './parsePage.js'
import type { ParsedPage, RouteIndexMap } from './types.js'

/**
 * 构建路由索引映射表
 *
 * 将页面列表转换为 RouteIndexMap 对象，包含每个路由的名称和路径作为键，以及对应的参数类型信息作为值。
 *
 * @param pages - 解析后的页面列表
 * @returns 路由索引映射表
 */
function buildRouteIndexMap(pages: ParsedPage[]): RouteIndexMap {
  const map: RouteIndexMap = {}

  /**
   * 递归处理单个页面及其子页面
   *
   * @param page - 要处理的页面
   */
  function processPage(page: ParsedPage): void {
    const params = extractParamsFromPath(page.path)
    const entry =
      params.length > 0
        ? { params: params.reduce((acc, p) => ({ ...acc, [p]: 'string | number' }), {}) }
        : {}

    // 同时使用 name 和 path 作为键，支持两种导航方式
    map[page.name] = entry
    map[page.path] = entry

    // 递归处理子路由
    for (const child of page.children) {
      processPage(child)
    }
  }

  for (const page of pages) {
    processPage(page)
  }

  return map
}

/**
 * 格式化单个路由索引条目
 *
 * @param key - 路由名称或路径
 * @param value - 路由索引条目值
 * @returns 格式化后的条目字符串
 */
function formatRouteIndexEntry(
  key: string,
  value: { params?: Record<string, string | number> }
): string {
  if (value.params && Object.keys(value.params).length > 0) {
    const paramsStr = Object.entries(value.params)
      .map(([k, v]) => `${k}: ${v}`)
      .join(', ')
    return `'${key}': { params: { ${paramsStr} } }`
  }
  return `'${key}': {}`
}

/**
 * 生成完整的 .d.ts 声明文件内容
 *
 * 包含文件头注释、模块扩展声明和具体的 RouteIndexMap 类型定义。
 * 生成的文件应该被用户项目的 TypeScript 配置引用。
 *
 * @param pages - 解析后的页面列表
 * @returns 完整的 .d.ts 文件内容
 */
export function generateFullDtsFile(pages: ParsedPage[]): string {
  const indexMap = buildRouteIndexMap(pages)

  const lines: string[] = []

  // 文件头注释
  lines.push('/* eslint-disable */')
  lines.push('/* prettier-ignore */')
  lines.push('// @ts-nocheck')
  lines.push('// Generated by vitarx-router. Do not modify this file.')
  lines.push('')

  // 模块扩展声明 - 扩展 vitarx-router 中的 RouteIndexMap 接口
  lines.push("declare module 'vitarx-router' {")
  lines.push('  // 自动生成的路由索引映射类型')
  lines.push('  interface RouteIndexMap {')

  const entries = Object.entries(indexMap)
  for (let i = 0; i < entries.length; i++) {
    const [key, value] = entries[i]
    const comma = i < entries.length - 1 ? ',' : ''
    const line = formatRouteIndexEntry(key, value)
    lines.push(`    ${line}${comma}`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
