/**
 * @fileoverview 类型生成模块
 *
 * 负责生成路由的 TypeScript 类型定义，用于提供 IDE 类型提示和编译时类型检查。
 * 与构建工具无关，可在任何 Node.js 环境中使用。
 */

import type { RouteNode } from '../types/index.js'
import { hasDynamicPath } from '../utils/index.js'

/**
 * 路由索引映射表
 *
 * 将路由名称和路径映射到对应的类型信息。
 * 支持通过名称或路径两种方式进行类型安全的导航。
 *
 * @example
 * ```typescript
 * // 生成的类型示例
 * interface RouteIndexMap {
 *   'home': {},
 *   '/': {},
 *   'user-id': { params: { id: string } },
 *   '/user/{id}': { params: { id: string } }
 * }
 *
 * // 使用示例
 * router.push({ index: 'user-id', params: { id: '123' } })
 * ```
 */
export interface ParsedRouteIndexMap {
  [key: string]: {
    /** 动态参数类型映射 */
    params?: Record<string, string | number>
  }
}

/**
 * 从路径中提取动态参数
 *
 * @param path - 路由路径
 * @returns 参数名称列表
 */
function extractParamsFromPath(path: string): string[] {
  const params: string[] = []
  const regex = /\{([^}?]+)(\?)?}/g
  let match

  while ((match = regex.exec(path)) !== null) {
    params.push(match[1])
  }

  return params
}

/**
 * 判断路由是否需要注册
 *
 * @param route - 路由信息
 * @returns {boolean} 是否需要注册
 */
function shouldRegisterRoute(route: RouteNode): boolean {
  const isGroup = route.children?.length
  const hasRedirect = route.redirect !== undefined
  return !isGroup || hasRedirect
}

/**
 * 解析 alias 路径
 *
 * @param alias - 别名路径
 * @param parentFullPath - 父级完整路径
 * @returns 解析后的完整路径
 */
function resolveAliasPath(alias: string, parentFullPath: string): string {
  const trimmedAlias = alias.trim()
  if (trimmedAlias === '') {
    return parentFullPath || '/'
  }
  if (trimmedAlias.startsWith('/')) {
    return trimmedAlias.replace(/\/+/g, '/').replace(/\/+$/, '') || '/'
  }
  if (!parentFullPath || parentFullPath === '/') {
    return '/' + trimmedAlias
  }
  return parentFullPath + '/' + trimmedAlias
}

/**
 * 格式化单个路由索引条目
 *
 * @param key - 路由键名
 * @param value - 路由条目值
 * @returns 格式化后的代码字符串
 */
function formatRouteIndexEntry(
  key: string,
  value: { params?: Record<string, string | number> }
): string {
  if (value.params && Object.keys(value.params).length > 0) {
    const paramsStr = Object.entries(value.params)
      .map(([k, v]) => `${k}: ${v}`)
      .join(', ')
    return `'${key}': { params: { ${paramsStr} } }`
  }
  return `'${key}': {}`
}

/**
 * 递归处理单个页面及其子页面
 *
 * @param map - 路由索引映射表
 * @param route - 页面信息
 * @param parentFullPath - 父级完整路径
 */
function processPage(
  map: ParsedRouteIndexMap,
  route: RouteNode,
  parentFullPath: string = ''
): void {
  const currentPath = route.fullPath
  if (shouldRegisterRoute(route)) {
    const params = extractParamsFromPath(route.fullPath)
    const entry =
      params.length > 0
        ? { params: params.reduce((acc, p) => ({ ...acc, [p]: 'string | number' }), {}) }
        : {}

    // 命名路由
    if (route.name) map[route.name] = entry

    if (!hasDynamicPath(currentPath)) {
      map[currentPath] = entry
    }
    if (route.alias) {
      const aliases = Array.isArray(route.alias) ? route.alias : [route.alias]
      for (const alias of aliases) {
        const aliasPath = resolveAliasPath(alias, parentFullPath)
        if (aliasPath && !hasDynamicPath(aliasPath)) {
          map[aliasPath] = entry
        }
      }
    }
  }

  if (route.children) {
    for (const child of route.children) {
      processPage(map, child, currentPath)
    }
  }
}
/**
 * 构建路由索引映射表
 *
 * @param routes - 页面列表
 * @returns 路由索引映射表
 */
function buildRouteIndexMap(routes: RouteNode[]): ParsedRouteIndexMap {
  const map: ParsedRouteIndexMap = {}
  for (const page of routes) {
    processPage(map, page)
  }
  return map
}

/**
 * 生成完整的 .d.ts 声明文件内容
 *
 * @param routes - 解析后的页面列表
 * @returns 完整的 .d.ts 文件内容
 */
export function generateDtsCode(routes: RouteNode[]): string {
  const moduleName = 'vitarx-router'
  const indexMap = buildRouteIndexMap(routes)

  const lines: string[] = []
  lines.push('/// <reference types="vitarx-router/global" />')
  lines.push('/* eslint-disable */')
  lines.push('/* prettier-ignore */')
  lines.push('// @ts-nocheck')
  lines.push(`// Generated by VitarxFileRouter. Do not modify this file.`)
  lines.push('')

  lines.push(`declare module '${moduleName}' {`)
  lines.push('  // 自动生成的路由索引映射类型')
  lines.push('  interface RouteIndexMap {')

  const entries = Object.entries(indexMap)
  for (let i = 0; i < entries.length; i++) {
    const [key, value] = entries[i]
    const comma = i < entries.length - 1 ? ',' : ''
    const line = formatRouteIndexEntry(key, value)
    lines.push(`    ${line}${comma}`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')

  return lines.join('\n')
}
