/// <reference types="vitarx-router/global" />
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by VitarxFileRouter. Do not modify this file.

declare module 'vitarx-router' {
  // 自动生成的路由索引映射类型
  interface RouteIndexMap {
    '/about': {},
    '/admin': {},
    '/admin/posts': {},
    '/admin/users': {},
    '/contact': {},
    'custom-route-demo': {},
    '/custom-route': {},
    '/': {},
    '/multi-view': {},
    'post-slug': { params: { slug: string | number } },
    'user-id': { params: { id: string | number } },
    '/users': {},
    '/users/profile': {},
    '/users/settings': {}
  }
}

export {}