/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vitarx-router. Do not modify this file.

declare module 'vitarx-router' {
  // 自动生成的路由索引映射类型
  interface RouteIndexMap {
    '': {},
    '/': {},
    'About': {},
    '/About': {}
  }
}

export {}