/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vitarx-router. Do not modify this file.

declare module 'vitarx-router' {
  // 自动生成的路由索引映射类型
  interface RouteIndexMap {
    'index': {},
    '/': {},
    'users-settings': {},
    '/users/settings': {},
    'about': {},
    '/about': {},
    'admin-index': {},
    '/admin': {},
    'admin-posts': {},
    'posts': {},
    'admin-users': {},
    'users': {},
    'contact': {},
    '/contact': {},
    'custom-route-demo': {},
    '/custom-route': {},
    'multi-view': {},
    '/multi-view': {},
    'users-index': {},
    '/users': {},
    'users-profile': {},
    'profile': {},
    'post-slug': { params: { slug: string | number } },
    'user-id': { params: { id: string | number } }
  }
}

export {}