/**
 * @fileoverview 类型生成模块测试
 *
 * 测试路由 TypeScript 类型定义生成功能，包括：
 * - generateDtsCode 声明文件生成
 * - 静态路由类型
 * - 动态参数路由类型
 * - 嵌套路由类型
 * - 别名路由类型
 * - 重定向路由类型
 */
import { describe, expect, it } from 'vitest'
import { generateDtsCode } from '../../../src/file-router/generator/generateTypes.js'
import type { RouteNode } from '../../../src/file-router/types/route.js'

describe('generator/generateTypes', () => {
  describe('generateDtsCode', () => {
    it('应该生成正确的文件头', () => {
      const result = generateDtsCode([])
      expect(result).toContain('/// <reference types="vitarx-router/global" />')
      expect(result).toContain('/* eslint-disable */')
      expect(result).toContain('/* prettier-ignore */')
      expect(result).toContain('// @ts-nocheck')
      expect(result).toContain('Generated by VitarxFileRouter')
    })

    it('应该生成正确的模块声明结构', () => {
      const result = generateDtsCode([])
      expect(result).toContain("declare module 'vitarx-router' {")
      expect(result).toContain('interface RouteIndexMap {')
      expect(result).toContain('}')
      expect(result).toContain('export {}')
    })

    it('应该为空路由列表生成空的 RouteIndexMap', () => {
      const result = generateDtsCode([])
      const mapSection = result.match(/interface RouteIndexMap \{([\s\S]*?)}/)?.[1]
      expect(mapSection?.trim()).toBe('')
    })

    it('应该为静态路由生成类型条目', () => {
      const routes: RouteNode[] = [{ path: '/', fullPath: '/', name: 'home' }]
      const result = generateDtsCode(routes)
      expect(result).toContain("'home': {}")
      expect(result).toContain("'/': {}")
    })

    it('应该为动态参数路由生成 params 类型', () => {
      const routes: RouteNode[] = [{ path: '/user/{id}', fullPath: '/user/{id}', name: 'user-id' }]
      const result = generateDtsCode(routes)
      expect(result).toContain("'user-id': { params: { id: string | number } }")
    })

    it('应该不为动态路径生成路径索引', () => {
      const routes: RouteNode[] = [{ path: '/user/{id}', fullPath: '/user/{id}', name: 'user-id' }]
      const result = generateDtsCode(routes)
      expect(result).not.toContain("'/user/{id}'")
    })

    it('应该为可选动态参数生成类型', () => {
      const routes: RouteNode[] = [
        { path: '/page/{id?}', fullPath: '/page/{id?}', name: 'page-id' }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'page-id': { params: { id: string | number } }")
    })

    it('应该为多个动态参数生成类型', () => {
      const routes: RouteNode[] = [
        {
          path: '/user/{userId}/post/{postId}',
          fullPath: '/user/{userId}/post/{postId}',
          name: 'user-post'
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain(
        "'user-post': { params: { userId: string | number, postId: string | number } }"
      )
    })

    it('应该为嵌套路由生成类型（带重定向的父路由）', () => {
      const routes: RouteNode[] = [
        {
          path: '/',
          fullPath: '/',
          name: 'home',
          redirect: '/about',
          children: [{ path: 'about', fullPath: '/about', name: 'about' }]
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'home': {}")
      expect(result).toContain("'/': {}")
      expect(result).toContain("'about': {}")
      expect(result).toContain("'/about': {}")
    })

    it('应该不为纯分组路由（无重定向）生成父级类型', () => {
      const routes: RouteNode[] = [
        {
          path: '/',
          fullPath: '/',
          name: 'home',
          children: [{ path: 'about', fullPath: '/about', name: 'about' }]
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).not.toContain("'home': {}")
      expect(result).not.toContain("'/': {}")
      expect(result).toContain("'about': {}")
      expect(result).toContain("'/about': {}")
    })

    it('应该为带别名的路由生成类型', () => {
      const routes: RouteNode[] = [
        { path: '/home', fullPath: '/home', name: 'home', alias: '/index' }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'home': {}")
      expect(result).toContain("'/home': {}")
      expect(result).toContain("'/index': {}")
    })

    it('应该为多个别名生成类型', () => {
      const routes: RouteNode[] = [
        { path: '/home', fullPath: '/home', name: 'home', alias: ['/index', '/start'] }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'/index': {}")
      expect(result).toContain("'/start': {}")
    })

    it('应该为带重定向的分组路由生成类型', () => {
      const routes: RouteNode[] = [
        {
          path: '/admin',
          fullPath: '/admin',
          name: 'admin',
          redirect: '/admin/dashboard',
          children: [{ path: 'dashboard', fullPath: '/admin/dashboard', name: 'admin-dashboard' }]
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'admin': {}")
      expect(result).toContain("'/admin': {}")
      expect(result).toContain("'admin-dashboard': {}")
      expect(result).toContain("'/admin/dashboard': {}")
    })

    it('应该不为无重定向的纯分组路由生成类型', () => {
      const routes: RouteNode[] = [
        {
          path: '/admin',
          fullPath: '/admin',
          children: [{ path: 'dashboard', fullPath: '/admin/dashboard', name: 'admin-dashboard' }]
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).not.toContain("'admin'")
      expect(result).not.toContain("'/admin'")
      expect(result).toContain("'admin-dashboard': {}")
    })

    it('应该为无名称的路由生成路径索引', () => {
      const routes: RouteNode[] = [{ path: '/about', fullPath: '/about' }]
      const result = generateDtsCode(routes)
      expect(result).toContain("'/about': {}")
    })

    it('应该正确处理别名路径解析', () => {
      const routes: RouteNode[] = [
        {
          path: '/user',
          fullPath: '/user',
          name: 'user',
          alias: 'profile'
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'/user': {}")
      expect(result).toContain("'/profile': {}")
    })

    it('应该正确处理以斜杠开头的别名', () => {
      const routes: RouteNode[] = [
        {
          path: '/user',
          fullPath: '/user',
          name: 'user',
          alias: '/account'
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'/account': {}")
    })

    it('应该正确处理空别名', () => {
      const routes: RouteNode[] = [
        {
          path: '/user',
          fullPath: '/user',
          name: 'user',
          alias: '  '
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'/user': {}")
      expect(result).toContain("'user': {}")
    })

    it('应该正确处理多级嵌套路由', () => {
      const routes: RouteNode[] = [
        {
          path: '/',
          fullPath: '/',
          name: 'root',
          redirect: '/user',
          children: [
            {
              path: 'user',
              fullPath: '/user',
              name: 'user',
              redirect: '/user/{id}',
              children: [{ path: '{id}', fullPath: '/user/{id}', name: 'user-id' }]
            }
          ]
        }
      ]
      const result = generateDtsCode(routes)
      expect(result).toContain("'root': {}")
      expect(result).toContain("'user': {}")
      expect(result).toContain("'user-id': { params: { id: string | number } }")
      expect(result).toContain("'/user': {}")
    })
  })
})
